<a href="https://colab.research.google.com/github/nanthini-1990/GitHubWorkshop/blob/main/Data_Merging_and_Lookup_Operations_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
# Data Merging and Lookup Operations with Pandas

#Student Name: Nanthini M

import pandas as pd
import numpy as np

# TASK 1: Data Preparation and Missing Value Handling

In [18]:

# Students DataFrame
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}

students = pd.DataFrame(students_data)


# Enrollments DataFrame
enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}

enrollments = pd.DataFrame(enrollments_data)


# Scores DataFrame
scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}

scores = pd.DataFrame(scores_data)


print("Students DataFrame:")
display(students)

Students DataFrame:

   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com       None
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi

In [19]:
# Null Value Analysis
print("Null Value Analysis")

null_counts = students.isnull().sum()
null_percent = (students.isnull().sum() / len(students)) * 100

for col in students.columns:
    print(f"Column: {col}, Nulls: {null_counts[col]} ({null_percent[col]:.2f}%)")

Null Value Analysis
Column: student_id, Nulls: 0 (0.00%)
Column: name, Nulls: 1 (14.29%)
Column: email, Nulls: 1 (14.29%)
Column: city, Nulls: 1 (14.29%)

In [20]:
# Handle Missing Values
# Fill missing city
students['city'] = students['city'].fillna('Unknown')

# Drop rows where name is missing
students_clean = students.dropna(subset=['name'])

print("Cleaned Students DataFrame")
display(students_clean)

Cleaned Students DataFrame

   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi

## TASK 2: Multiple Join Operations

In [21]:
inner_join = pd.merge(students_clean, enrollments, on='student_id', how='inner')

print("Inner Join Result:")
display(inner_join)

print("Number of students:", len(inner_join))

Inner Join Result:

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10

Number of students: 3

In [22]:
left_join = pd.merge(students_clean, enrollments, on='student_id', how='left')

print("Left Join Result")
display(left_join)

print("Total rows:", len(left_join))

Left Join Result

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,104,David,None,Mumbai,NaN,NaN
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,NaN,NaN
5,107,Grace,grace@email.com,Delhi,NaN,NaN

Total rows: 6

In [23]:
right_join = pd.merge(students_clean, enrollments, on='student_id', how='right')

display(right_join)

print("Total rows:", len(right_join))

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,108,NaN,NaN,NaN,AI,2024-02-15
5,109,NaN,NaN,NaN,Python,2024-03-01

Total rows: 6

In [24]:
outer_join = pd.merge(students_clean, enrollments, on='student_id', how='outer', indicator=True)

display(outer_join)

print("Total rows:", len(outer_join))

,student_id,name,email,city,course_name,enrollment_date,_merge
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15,both
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20,both
2,103,NaN,NaN,NaN,Python,2024-02-01,right_only
3,104,David,None,Mumbai,NaN,NaN,left_only
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10,both
5,106,Frank,frank@email.com,Chennai,NaN,NaN,left_only
6,107,Grace,grace@email.com,Delhi,NaN,NaN,left_only
7,108,NaN,NaN,NaN,AI,2024-02-15,right_only
8,109,NaN,NaN,NaN,Python,2024-03-01,right_only

Total rows: 9

In [25]:
missing_rows = outer_join[(outer_join['name'].isnull()) | (outer_join['course_name'].isnull())]

display(missing_rows)

,student_id,name,email,city,course_name,enrollment_date,_merge
2,103,NaN,NaN,NaN,Python,2024-02-01,right_only
3,104,David,None,Mumbai,NaN,NaN,left_only
5,106,Frank,frank@email.com,Chennai,NaN,NaN,left_only
6,107,Grace,grace@email.com,Delhi,NaN,NaN,left_only
7,108,NaN,NaN,NaN,AI,2024-02-15,right_only
8,109,NaN,NaN,NaN,Python,2024-03-01,right_only

In [26]:
outer_join['_merge'].value_counts()

_merge
left_only     3
right_only    3
both          3
Name: count, dtype: int64

## TASK 3: Lookup Operations and Automation

In [27]:
score_dict = dict(zip(scores.student_id, scores.exam_score))

students_clean['exam_score'] = students_clean['student_id'].map(score_dict)

display(students_clean[['student_id','name','exam_score']])

/tmp/ipykernel_638/2049901889.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students_clean['exam_score'] = students_clean['student_id'].map(score_dict)

   student_id   name  exam_score
0         101  Alice        85.0
1         102    Bob        92.0
3         104  David        78.0
4         105   Emma        88.0
5         106  Frank        95.0
6         107  Grace         NaN

In [28]:
merge_scores = pd.merge(students_clean.drop(columns=['exam_score'], errors='ignore'),
                        scores,
                        on='student_id',
                        how='left')

display(merge_scores[['student_id','name','exam_score']])

   student_id   name  exam_score
0         101  Alice        85.0
1         102    Bob        92.0
2         104  David        78.0
3         105   Emma        88.0
4         106  Frank        95.0
5         107  Grace         NaN

In [29]:
def auto_merge(df1, df2, join_type, key_column):

    merged = pd.merge(df1, df2, how=join_type, on=key_column)

    return {
        "result_df": merged,
        "row_count": len(merged),
        "join_type": join_type
    }

In [30]:
test1 = auto_merge(students_clean, enrollments, "inner", "student_id")
test2 = auto_merge(students_clean, enrollments, "left", "student_id")

print("Join Type:", test1['join_type'])
print("Rows:", test1['row_count'])
display(test1['result_df'].head())

print("Join Type:", test2['join_type'])
print("Rows:", test2['row_count'])
display(test2['result_df'].head())

Join Type: inner
Rows: 3

,student_id,name,email,city,exam_score,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,85.0,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,92.0,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,88.0,Machine Learning,2024-02-10

Join Type: left
Rows: 6

,student_id,name,email,city,exam_score,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,85.0,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,92.0,Data Science,2024-01-20
2,104,David,None,Mumbai,78.0,NaN,NaN
3,105,Emma,emma@email.com,Unknown,88.0,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,95.0,NaN,NaN

## Submission Details

Student Name: Nanthini M

Notebook Link: https://github.com/nanthini-1990/GitHubWorkshop

All Tasks Completed: Yes

Additional Notes:
This notebook demonstrates handling missing values, performing join operations, using lookup functions, and automating merge tasks using pandas.