<a href="https://colab.research.google.com/github/nanthini-1990/GitHubWorkshop/blob/main/Pandas_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Step 1: Import the Pandas Library
#Explanation: This step imports the pandas library, which is used for creating and analyzing DataFrames.

import pandas as pd

In [2]:
#Step 2: Create a DataFrame Using the Student Data
#Explanation: This step creates a pandas DataFrame using the given student dataset.

data = {
    "StudentID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Alice","Bob","Charlie","Diana","Ethan","Fiona","George","Hannah","Ivan","Julia"],
    "Age": [20,21,19,22,20,21,23,19,22,20],
    "Marks": [88,75,92,65,78,85,70,95,60,80],
    "Grade": ["A","B","A","C","B","A","B","A","C","B"]
}

df = pd.DataFrame(data)

df

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

In [3]:
#Step 3: Save the DataFrame as a CSV File
#Explanation: This step saves the DataFrame into a CSV file named students.csv.

df.to_csv("students.csv", index=False)

print("CSV file saved successfully.")

CSV file saved successfully.

In [4]:
#Step 4: Reload the CSV File into a New DataFrame
#Explanation: This step reads the saved CSV file and loads it into a new DataFrame.

df_new = pd.read_csv("students.csv")
df_new

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

In [6]:
#Step 5: Display the First 3 Rows and Display Statistical Summary etc..,.
#Explanation: This step explores the dataset by displaying the first three rows, statistical summary, shape, data types, and overall DataFrame information using head(), describe(), shape, dtypes, and info().

df_new.head(3)
df_new.describe()
df_new.shape
df_new.dtypes
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [7]:
#Complete Program code in one block

# Import pandas library
import pandas as pd

# Create student data
data = {
    "StudentID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Alice","Bob","Charlie","Diana","Ethan","Fiona","George","Hannah","Ivan","Julia"],
    "Age": [20,21,19,22,20,21,23,19,22,20],
    "Marks": [88,75,92,65,78,85,70,95,60,80],
    "Grade": ["A","B","A","C","B","A","B","A","C","B"]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save DataFrame as CSV
df.to_csv("students.csv", index=False)

# Reload CSV file
df_new = pd.read_csv("students.csv")

# Display first 3 rows
print("First 3 Rows:")
print(df_new.head(3))

# Display statistical summary
print("\nStatistical Summary:")
print(df_new.describe())

# Display shape of DataFrame
print("\nShape of DataFrame:")
print(df_new.shape)

# Display data types
print("\nData Types:")
print(df_new.dtypes)

# Display complete information
print("\nDataFrame Info:")
df_new.info()

First 3 Rows:
   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A

Statistical Summary:
       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  20.700000  78.800000
std      3.02765   1.337494  11.535453
min    101.00000  19.000000  60.000000
25%    103.25000  20.000000  71.250000
50%    105.50000  20.500000  79.000000
75%    107.75000  21.750000  87.250000
max    110.00000  23.000000  95.000000

Shape of DataFrame:
(10, 5)

Data Types:
StudentID     int64
Name         object
Age           int64
Marks         int64
Grade        object
dtype: object

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes